const ActionTypes = {
  FETCH_BANNERS: 'FETCH_BANNERS',
  FETCH_START_IMAGE: 'FETCH_START_IMAGE',
  RECIEVE_BANNERS: 'RECIEVE_BANNERS',
  RECIEVE_START_IMAGE: 'RECIEVE_START_IMAGE',
}

export default ActionTypes
